print("It's time for some Mad Libs! Are you ready?")
input()
print("Let's go!")
noun1 = input("First, I need a singular noun: ")
name = input("Next, I need a name for our protagonist: ")
noun2 = input("Let's add another noun to the party: ")
noun3 = input("And another noun: ")
adjective1 = input("It's time to choose an adjective: ")
adjective2 = input("And another: ")
adjective3 = input("And a third: ")
type_of_person = input("Please enter in a type of person, for example, mother, friend, firefighter: ")
adjective4 = input("And now, one last adjective: ")
phrase = input("The last thing we need is a phrase for our protagonist to say: ")
print("All right, here's our story!")


print("There once was a(n) " + noun1 + " named " + name + ". ")
print(name + " was a pretty ordinary " + noun2 + ", living a pretty normal life, until one day, they received a(n) " + noun3 + ".")
print("This changed their entire life. What once was " + adjective1 + " had become " + adjective2 + ".")
print(name + " felt " + adjective3 + " about this, and went to talk to their " + type_of_person + " about it.")
print("The " + type_of_person + ", however, felt differently. \"" + name + ",\" they said, \"a(n) " + noun3 + " is many a splendored thing.\"")
print(name + " realized that this statement was " + adjective4 + ", and said, \"" + phrase + "\"!")
print("The End.")
